---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.2
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      NER_INFERENCE_API: 'http://ner-transformers:8080'
      OPENAI_APIKEY: 'OPENAI_API_KEY'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,ner-transformers'
      CLUSTER_HOSTNAME: 'node1'
  ner-transformers:
      build:
        context: ./ner_module
        dockerfile: ner.Dockerfile
        args:
          MODEL_NAME: "Dizex/FoodBaseBERT-NER"
      environment:
        ENABLE_CUDA: '0'
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
...